version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - ./data/odoo-data:/var/lib/odoo
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/extra-addons:rw
    tty: true
    command: -- --dev=reload
    restart: always
